server {
	listen 80;
	server_name _;
	root /usr/share/nginx/html;

	location = /index.json {
		add_header Cache-Control "no-store" always;
		add_header Access-Control-Allow-Origin "*" always;
		try_files $uri =404;
	}

	location ~ \.zip$ {
		default_type application/zip;
		add_header Cache-Control "no-store" always;
		add_header Access-Control-Allow-Origin "*" always;
		try_files $uri =404;
	}

	location = /revenge.bundle {
		default_type application/octet-stream;
		add_header Cache-Control "no-store" always;
		add_header Access-Control-Allow-Origin "*" always;
		try_files $uri =404;
	}

	location / {
		return 404;
	}
}
